dist: trusty
language: go

jdk:
- 1.11.x

env:
  global:
    # GITHUB Token
    - secure: kvmwo/c82SUB18qrjQ2WzVri574PfmujoM5tdMrzCj6aj09hVPAgqrl5m2yqKpjZ5X8GRN5J6DFhr07u3uPFB0Cojo41mC0CrM65KChDnwHMkSC8icAs4MWhuqW0Jj33Wi6cfLqW9scWw5ZNrnCTIZ1zQNOeaY8nPXsEClQBNoy/uqWQ7lWfG886humTWj7QRfKqsOjopwp7/zuAF7yJkfvgwl+cdje2bsR46pNR0GxTfCv8x1O7vYrhGE76+UgkboUXnh17I29Rnw09NN5Riiba/vXXEx9atuazokbEwzt4A3ImtkoSuhAM1d+GBFrYcwcWWDQh+nkxLLHlemiUNE3ER4vZgoSbT85pYLnSfaMml/+XCeQNYtAAWRl4vgys9S6xHCqHPpch3VNMtxYWutKE8D1BLvp/YV/CSigTyc9TSXeR8WM/dq9+1gsacT+dLPPSSqkd+iVwLigCMa5BmgH+lgib3Fs4F5BuvTyl005G9fVQvk5cyyp94i3bp7wN8N6Pz7d/gbhdoutSFDB3jSY981VLSIeeRBHyfcvlQ7fXg35ZmbHtmw857PnCOqZnIyZS+BmNv/pt/t3/xZKP4FfjMf3Fl3uvbbkHF6qRaP96NRPwDNz0c8xd8x54GCeTXDD3JHPIgRkr7g7RNJKMtgXqCLhvRSoeqZ7idRA1l+I=

script:
 - go get ./...
 - go build
 - zip -r build-${TRAVIS_TAG}.zip le_lambda

deploy:
  provider: releases
  api_key: ${GITHUB_ACCESS_TOKEN}
  file:
    - build-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
