dist: trusty
language: go

jdk:
- 1.11.x

script:
 - go get ./...
 - go build
 - zip -r build-${TRAVIS_TAG}.zip le_lambda

deploy:
  provider: releases
  api_key:
    secure: GnhChc/fB0pK7bARdbQ/Z/cULFxGmLvGHb+dtTrq31/2ggwAfTcjNkLdGrIKOKftYRLNvrzRN0B7qinsnTD1LRssn9OdDIAo+nlfBj3ZKU/gorKqJNF1RT8hYA9N4TMqM58AAqPa/AXdKg/Y43D9/2KTS03lrkEM2dCtSUYtoRew/SCmER1KAuH0qO3liOmHGBpSRpCRjkNoTCS7RnPIPltwGQh4pc23KwXZ+GYj5ng8nHTUIHMDiXUUWTnkXxb1E6UWI/dCbSHrP40PF6cxSLO+6H5KC9HXYEnyAk69MLAyGlGWfTSsX+QqJt1zVIgiFGWj+nDnipTo3dhCfXrlPJfwEHMfdlT/hKxDKqg8I7snOheDIh/Q+rQ0tevv2nBJn3byI9rAj3qPtdwyYOuIWRfFkMM7Qs6FUJEk4oyCRCKFCawmr26s1EcGnsnxtW2K9UZMJ8WWnc4uSFPhZvmx4oIxhGRPQkMCKFaYYjRjV51NRJ3iMhkontCSYh/9oni0qFKUWmyTL7peUC+rfvkY+hiA9/vHAhPNizPrbzrugt3OHaynVoEnqXIyNTEZs/S1voOQCKb6dOUPjXY02jRzDhkHQwy5tapfJP+KqPYrmNvJZKUv7a31QtcVgIoCDwK9jlGuqeRChUvPCrTJIh7h/Bline0Iwkpc1laggvjoC64=
  file:
    - build-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
