dist: trusty
language: go

jdk:
- 1.11.x

script:
 - go get ./...
 - go build
 - zip -r build-${TRAVIS_TAG}.zip le_lambda

deploy:
  provider: releases
  api_key:
    secure: fBTO7H273D9Oooy0MLfA5N20PNpDNkSnI3jQhjFoo4fuAd4vtpGEl/h4n7Rv8ifwinuQCM2qMcUA18iZ93S7D+u8ZW5/KBvyD1EFhK6K1WpgZrija00tyqP0g8Ha/cf6jS8b6L7VRV/u0CSduyQNpQQ6tOS450bReR6Cx+70x7N3fsqgTFLGG9a5oGoxzabgBPo0MLKtnSzLUlxbV0t7UDBbcT+qzc03RmEc4m34jU3MjYTxs/exEDv2KXlefcj0UxLaGOoOjhvF5UEgVLQVgtEaUanOiG4FFAxeJjcquEtPdnLAQaTPeF4QdZ9pyXAk1idh//USTCC/1cqviL8i4MWD7ijVG2sVLk50NzsfYZ1V06nXEqgrI3WW8fYzLwhcXGowmwklAfB/5GHdqNRk/AY/TYSiPDMu4YSjUUJoHjP65e0jlJ+zHG75UKiSMLpJPvR3xtnQhO5XrdNs3pEnaBi3Nwo4ma/Cl5ub5k2+dPiKQBOKhr/bcWF5zQy5QCwfcFb+aO5pi47iZSHnbPwplA8n+4xhEocHDXWs4PjCMN/LVWbVOtABZqFEIkxVSHo0jIiESvlzfwP4bd39dIJlkNuJhOALBYwsH8u145zEdkCzXHdirGNvPvC/XxaWrDKyz3kec/9e3HlVw2xTFGLZKoE5zgPowFBG5Mru79WaO20=
  file:
    - build-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
