dist: trusty
language: go

jdk:
- 1.11.x

env:
  global:
    # GITHUB Token
    - secure: lF7UeVH69OoOZZH02cuAVYR0F/hF5MyqoBM0i7/ysw1iHMXPd/no3NdJyHddjKnUaxpAjprPng6YPA2bvU2ZNgDc+cS+OLcblfpyliLme46dZVxVMWVr0Nb+OuCXr08mpv8H18RBGnfjXMSnQnPwIniDP35XiIcZb2x/P1r43TQm5twQysq1AbLtEOrDj2ncPg5r1IwyoGNC8SC8hi37bzSiONze6zHe4WSkgQ8Vu66o4n+D9nAUvIJcagLQFhk3b2ZlkJFwFKoxz4YSGrfI0nSpD8UL3G9I2bh3Rx4KfZGSw9o0ZE1S803y85o/le3lLtssM0pns4EYSyQgXdsacA52HVNzMHRR9NxUbJ0KWWMTR8rcdpfyVZoq39wCZH2vQjQ1aFiypUxGWoSSLK1f3drzsShUS8qsmwtwguTw7w3nkUVDRJvr+UgKsZ0DWDSxlBiRhwKy3Rwjz6+F5Xvze7+LFlxN3hPPHMnTYT2UiQZvRexmq5nQh1RFrsVQ+9Pf09yi+t0VnVRMXs7SgFuuGK2HG5lLtbg0KPFdshm+/pK2b4Dx5FXYe5C7nn/giP+zLoXMxtG0YaEE4shwITe06Y72q7UDB/KK3/l76Z0MbTT43jh7Y3ikE/tUzJInW5SB6OrmbZavyp+425ptErmu0qYbVZ1l+z4RIFcFVIxGmQc=

script:
 - go get ./...
 - go build
 - zip -r build-${TRAVIS_TAG}.zip le_lambda

deploy:
  provider: releases
  api_key: ${GITHUB_ACCESS_TOKEN}
  file:
    - build-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
