dist: trusty
language: go
go:
 - 1.11.x

script:
 - go get ./...
 - go build
 - zip -r build-${TRAVIS_TAG}.zip le_lambda

deploy:
  provider: releases
  api_key:
    secure: UXytg8xEjIatwOGbXCXS7zxHj+3yEubrggPw507neCx1tZXn1zm83zXCamxsG6IsubDQ8rVtqr7LWs5JL70P5TXLPcWurVrAc+Mefv/q8w8FbKf3VhwHqn0JseMHgz1wg/Uf2jmkkfs8Zx2Fb1RhyzO0vJNGaeIwzS1OPNV4LykJeHodmT3F8sPdwXbZzXHabMzfUb2yeGkSZFQoer7np2AePsIv7ncOo8+CfK0nKQlCqTd/3ibYZjXGV0Y571gGZDQnn/508h/1i/H+RRZ2LgT+0q4AIQiHcqcGVHfwTscOffKM6NNMqtWuBoxsVxRABIz+HCvL59nGlwr2+eomw+1j2dOmcqMb0xOb4bDoO6V017Ku5b6bhwJp8XTTE711RgQDqlZqu2b+oCgUbUz0zz2JjF8/iwEgdVQIh7rqw4o9imWDsCWBKhBoluGyRl/NlZ6WQarjJJ7lLnDhqrkB54eK5OXi7CruJ9ZkbZDrjYBdWzhC6AaIp+ZBXkXn0smgUXO7q15s8twKVCkkPt73VKCSmldVlq1oLuAfk1Dy/TUpIRCiyufzFjba9TWDhsui+U20nxWXOFt7Ps+9Jq8PdL7WCLvnwSFFNV5kv7M0vfQLN3/h8B5LarnOFIxzzfxoouTdnoZ/ZS7GkNSsPl/GNTDqeaVYefVMCys9nOL1mxA=
  file: build-${TRAVIS_TAG}.zip
  on:
    repo: Tweddle-SE-Team/le_lambda
    tags: true
